### ISSUE TITLE
Update repo description: http://commonaccord.org

### ISSUE THREAD

**Issue by jonathancross** [CommonAccord/Cmacc-Org#20]
Per https://github.com/CommonAccord/Site-Org/issues/42, AFAICT this seems to be the correct repo for commonaccord.org?  If so, please add that website to the repo description and remove from  CommonAccord/Site-Org repo.

**Comment by HazardJ** [comment]
Absolutely.  Thanks!  You are among the first really determined visitors.

**Comment by jonathancross** [comment]
> first really determined visitors.

Honestly, I'm a web developer and thought the site was broken because it doesn't have css, etc.
I was annotating info presented by Pamela Morgan in [this video](https://www.youtube.com/watch?v=b7MOrbd1ioM&lc=z13oi3cbqwypydpm522ycxbo3vutvtplr) and came across Common Accord that way.  It seems that [the wordpress site](https://commonaccord.wordpress.com﻿) is much more active, so I linked to that in the end.
